* TTRPG-Hangout

This is, as of 2025-03-26, my latest attempt at building ttrpg-hangout.com.

- It's based on https://tedboy.github.io/flask/quickstart/quickstart1.html.
- The template stuff is from https://flask.palletsprojects.com/en/stable/tutorial/templates/.

The aim here is to make a minimalist version of ttrpg-hangout.com that uses routes and templates, no SQL (initially), and just loads html files from a directory.

* Starting it

#+begin_src bash
. ~/venvs/TTRPG-Hangout/bin/activate
./start.sh  # Will start it on 127.0.0.1:5000
#end_src

* Updating the pages

#+begin_src bash
. ~/venvs/RoamNotes/bin/activate
cd ~/devel/RoamNotes
make
#+end_src bash

* Status / Things that work

http://127.0.0.1:5000 is the front page, and it works and has navigation.
http://127.0.0.1:5000/article/springhaven etc also works. This has navigation.

* How the front page works

The front page is created from web.py, and rendered from a template called start.html. It gets two arguments - the "intro" which is read from the "Intro TTRPG-Hangout" page, and the table of contents which is read from "TOG TTRPG-Hangout" page. These are controlled by constants in web.py.

* Next steps

- Add hook function which updates all the pages
- Publish on pythonanywhere

* Reference

- https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox
